<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:kopr="http://kopr.ics.upjs.sk"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="reservation"
                  targetNamespace="http://kopr.ics.upjs.sk"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    targetNamespace="http://kopr.ics.upjs.sk">
            <xsd:include schemaLocation="reservation.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="ReservationRequest">
        <wsdl:part name="part" element="kopr:ReservationRequest" />
    </wsdl:message>

    <wsdl:message name="ReservationResponse">
        <wsdl:part name="part" element="kopr:ReservationResponse" />
    </wsdl:message>

    <wsdl:portType name="ReservationPortType">
        <wsdl:operation name="MakeReservation">
            <wsdl:input message="kopr:ReservationRequest" />
            <wsdl:output message="kopr:ReservationResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ReservationBinding"
                  type="kopr:ReservationPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="MakeReservation">
            <soap:operation
                    soapAction="http://kopr.ics.upjs.sk/MakeReservation" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ReservationService">
        <wsdl:port name="ReservationPort"
                   binding="kopr:ReservationBinding">
            <soap:address
                    location="http://localhost:8888/reservation" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
